apiVersion: v1
kind: Pod
metadata:
  name: debian-nginx
spec:
  containers:
  - name: debian
    image: debian
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        date >> /usr/share/nginx/html/index.html;
        sleep 1;
      done
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-data
    emptyDir: {}
